# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fred/Development/javachaos-aoc2021

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fred/Development/javachaos-aoc2021

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fred/Development/javachaos-aoc2021/CMakeFiles /home/fred/Development/javachaos-aoc2021/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fred/Development/javachaos-aoc2021/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aoc8

# Build rule for target.
aoc8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc8
.PHONY : aoc8

# fast build rule for target.
aoc8/fast:
	$(MAKE) -f CMakeFiles/aoc8.dir/build.make CMakeFiles/aoc8.dir/build
.PHONY : aoc8/fast

#=============================================================================
# Target rules for targets named aoc7

# Build rule for target.
aoc7: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc7
.PHONY : aoc7

# fast build rule for target.
aoc7/fast:
	$(MAKE) -f CMakeFiles/aoc7.dir/build.make CMakeFiles/aoc7.dir/build
.PHONY : aoc7/fast

#=============================================================================
# Target rules for targets named aoc10

# Build rule for target.
aoc10: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc10
.PHONY : aoc10

# fast build rule for target.
aoc10/fast:
	$(MAKE) -f CMakeFiles/aoc10.dir/build.make CMakeFiles/aoc10.dir/build
.PHONY : aoc10/fast

#=============================================================================
# Target rules for targets named aoc3_2

# Build rule for target.
aoc3_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc3_2
.PHONY : aoc3_2

# fast build rule for target.
aoc3_2/fast:
	$(MAKE) -f CMakeFiles/aoc3_2.dir/build.make CMakeFiles/aoc3_2.dir/build
.PHONY : aoc3_2/fast

#=============================================================================
# Target rules for targets named aoc6

# Build rule for target.
aoc6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc6
.PHONY : aoc6

# fast build rule for target.
aoc6/fast:
	$(MAKE) -f CMakeFiles/aoc6.dir/build.make CMakeFiles/aoc6.dir/build
.PHONY : aoc6/fast

#=============================================================================
# Target rules for targets named aoc2

# Build rule for target.
aoc2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc2
.PHONY : aoc2

# fast build rule for target.
aoc2/fast:
	$(MAKE) -f CMakeFiles/aoc2.dir/build.make CMakeFiles/aoc2.dir/build
.PHONY : aoc2/fast

#=============================================================================
# Target rules for targets named aoc3

# Build rule for target.
aoc3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc3
.PHONY : aoc3

# fast build rule for target.
aoc3/fast:
	$(MAKE) -f CMakeFiles/aoc3.dir/build.make CMakeFiles/aoc3.dir/build
.PHONY : aoc3/fast

#=============================================================================
# Target rules for targets named aoc1

# Build rule for target.
aoc1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc1
.PHONY : aoc1

# fast build rule for target.
aoc1/fast:
	$(MAKE) -f CMakeFiles/aoc1.dir/build.make CMakeFiles/aoc1.dir/build
.PHONY : aoc1/fast

#=============================================================================
# Target rules for targets named aoc5

# Build rule for target.
aoc5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc5
.PHONY : aoc5

# fast build rule for target.
aoc5/fast:
	$(MAKE) -f CMakeFiles/aoc5.dir/build.make CMakeFiles/aoc5.dir/build
.PHONY : aoc5/fast

#=============================================================================
# Target rules for targets named aoc

# Build rule for target.
aoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aoc
.PHONY : aoc

# fast build rule for target.
aoc/fast:
	$(MAKE) -f CMakeFiles/aoc.dir/build.make CMakeFiles/aoc.dir/build
.PHONY : aoc/fast

#=============================================================================
# Target rules for targets named binmat

# Build rule for target.
binmat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binmat
.PHONY : binmat

# fast build rule for target.
binmat/fast:
	$(MAKE) -f CMakeFiles/binmat.dir/build.make CMakeFiles/binmat.dir/build
.PHONY : binmat/fast

AOC.o: AOC.cpp.o

.PHONY : AOC.o

# target to build an object file
AOC.cpp.o:
	$(MAKE) -f CMakeFiles/aoc.dir/build.make CMakeFiles/aoc.dir/AOC.cpp.o
.PHONY : AOC.cpp.o

AOC.i: AOC.cpp.i

.PHONY : AOC.i

# target to preprocess a source file
AOC.cpp.i:
	$(MAKE) -f CMakeFiles/aoc.dir/build.make CMakeFiles/aoc.dir/AOC.cpp.i
.PHONY : AOC.cpp.i

AOC.s: AOC.cpp.s

.PHONY : AOC.s

# target to generate assembly for a file
AOC.cpp.s:
	$(MAKE) -f CMakeFiles/aoc.dir/build.make CMakeFiles/aoc.dir/AOC.cpp.s
.PHONY : AOC.cpp.s

AOC1.o: AOC1.cpp.o

.PHONY : AOC1.o

# target to build an object file
AOC1.cpp.o:
	$(MAKE) -f CMakeFiles/aoc1.dir/build.make CMakeFiles/aoc1.dir/AOC1.cpp.o
.PHONY : AOC1.cpp.o

AOC1.i: AOC1.cpp.i

.PHONY : AOC1.i

# target to preprocess a source file
AOC1.cpp.i:
	$(MAKE) -f CMakeFiles/aoc1.dir/build.make CMakeFiles/aoc1.dir/AOC1.cpp.i
.PHONY : AOC1.cpp.i

AOC1.s: AOC1.cpp.s

.PHONY : AOC1.s

# target to generate assembly for a file
AOC1.cpp.s:
	$(MAKE) -f CMakeFiles/aoc1.dir/build.make CMakeFiles/aoc1.dir/AOC1.cpp.s
.PHONY : AOC1.cpp.s

AOC10.o: AOC10.c.o

.PHONY : AOC10.o

# target to build an object file
AOC10.c.o:
	$(MAKE) -f CMakeFiles/aoc10.dir/build.make CMakeFiles/aoc10.dir/AOC10.c.o
.PHONY : AOC10.c.o

AOC10.i: AOC10.c.i

.PHONY : AOC10.i

# target to preprocess a source file
AOC10.c.i:
	$(MAKE) -f CMakeFiles/aoc10.dir/build.make CMakeFiles/aoc10.dir/AOC10.c.i
.PHONY : AOC10.c.i

AOC10.s: AOC10.c.s

.PHONY : AOC10.s

# target to generate assembly for a file
AOC10.c.s:
	$(MAKE) -f CMakeFiles/aoc10.dir/build.make CMakeFiles/aoc10.dir/AOC10.c.s
.PHONY : AOC10.c.s

AOC2.o: AOC2.cpp.o

.PHONY : AOC2.o

# target to build an object file
AOC2.cpp.o:
	$(MAKE) -f CMakeFiles/aoc2.dir/build.make CMakeFiles/aoc2.dir/AOC2.cpp.o
.PHONY : AOC2.cpp.o

AOC2.i: AOC2.cpp.i

.PHONY : AOC2.i

# target to preprocess a source file
AOC2.cpp.i:
	$(MAKE) -f CMakeFiles/aoc2.dir/build.make CMakeFiles/aoc2.dir/AOC2.cpp.i
.PHONY : AOC2.cpp.i

AOC2.s: AOC2.cpp.s

.PHONY : AOC2.s

# target to generate assembly for a file
AOC2.cpp.s:
	$(MAKE) -f CMakeFiles/aoc2.dir/build.make CMakeFiles/aoc2.dir/AOC2.cpp.s
.PHONY : AOC2.cpp.s

AOC3.o: AOC3.cpp.o

.PHONY : AOC3.o

# target to build an object file
AOC3.cpp.o:
	$(MAKE) -f CMakeFiles/aoc3.dir/build.make CMakeFiles/aoc3.dir/AOC3.cpp.o
.PHONY : AOC3.cpp.o

AOC3.i: AOC3.cpp.i

.PHONY : AOC3.i

# target to preprocess a source file
AOC3.cpp.i:
	$(MAKE) -f CMakeFiles/aoc3.dir/build.make CMakeFiles/aoc3.dir/AOC3.cpp.i
.PHONY : AOC3.cpp.i

AOC3.s: AOC3.cpp.s

.PHONY : AOC3.s

# target to generate assembly for a file
AOC3.cpp.s:
	$(MAKE) -f CMakeFiles/aoc3.dir/build.make CMakeFiles/aoc3.dir/AOC3.cpp.s
.PHONY : AOC3.cpp.s

AOC3_2.o: AOC3_2.cpp.o

.PHONY : AOC3_2.o

# target to build an object file
AOC3_2.cpp.o:
	$(MAKE) -f CMakeFiles/aoc3_2.dir/build.make CMakeFiles/aoc3_2.dir/AOC3_2.cpp.o
.PHONY : AOC3_2.cpp.o

AOC3_2.i: AOC3_2.cpp.i

.PHONY : AOC3_2.i

# target to preprocess a source file
AOC3_2.cpp.i:
	$(MAKE) -f CMakeFiles/aoc3_2.dir/build.make CMakeFiles/aoc3_2.dir/AOC3_2.cpp.i
.PHONY : AOC3_2.cpp.i

AOC3_2.s: AOC3_2.cpp.s

.PHONY : AOC3_2.s

# target to generate assembly for a file
AOC3_2.cpp.s:
	$(MAKE) -f CMakeFiles/aoc3_2.dir/build.make CMakeFiles/aoc3_2.dir/AOC3_2.cpp.s
.PHONY : AOC3_2.cpp.s

AOC5.o: AOC5.cpp.o

.PHONY : AOC5.o

# target to build an object file
AOC5.cpp.o:
	$(MAKE) -f CMakeFiles/aoc5.dir/build.make CMakeFiles/aoc5.dir/AOC5.cpp.o
.PHONY : AOC5.cpp.o

AOC5.i: AOC5.cpp.i

.PHONY : AOC5.i

# target to preprocess a source file
AOC5.cpp.i:
	$(MAKE) -f CMakeFiles/aoc5.dir/build.make CMakeFiles/aoc5.dir/AOC5.cpp.i
.PHONY : AOC5.cpp.i

AOC5.s: AOC5.cpp.s

.PHONY : AOC5.s

# target to generate assembly for a file
AOC5.cpp.s:
	$(MAKE) -f CMakeFiles/aoc5.dir/build.make CMakeFiles/aoc5.dir/AOC5.cpp.s
.PHONY : AOC5.cpp.s

AOC6.o: AOC6.cpp.o

.PHONY : AOC6.o

# target to build an object file
AOC6.cpp.o:
	$(MAKE) -f CMakeFiles/aoc6.dir/build.make CMakeFiles/aoc6.dir/AOC6.cpp.o
.PHONY : AOC6.cpp.o

AOC6.i: AOC6.cpp.i

.PHONY : AOC6.i

# target to preprocess a source file
AOC6.cpp.i:
	$(MAKE) -f CMakeFiles/aoc6.dir/build.make CMakeFiles/aoc6.dir/AOC6.cpp.i
.PHONY : AOC6.cpp.i

AOC6.s: AOC6.cpp.s

.PHONY : AOC6.s

# target to generate assembly for a file
AOC6.cpp.s:
	$(MAKE) -f CMakeFiles/aoc6.dir/build.make CMakeFiles/aoc6.dir/AOC6.cpp.s
.PHONY : AOC6.cpp.s

AOC7.o: AOC7.cpp.o

.PHONY : AOC7.o

# target to build an object file
AOC7.cpp.o:
	$(MAKE) -f CMakeFiles/aoc7.dir/build.make CMakeFiles/aoc7.dir/AOC7.cpp.o
.PHONY : AOC7.cpp.o

AOC7.i: AOC7.cpp.i

.PHONY : AOC7.i

# target to preprocess a source file
AOC7.cpp.i:
	$(MAKE) -f CMakeFiles/aoc7.dir/build.make CMakeFiles/aoc7.dir/AOC7.cpp.i
.PHONY : AOC7.cpp.i

AOC7.s: AOC7.cpp.s

.PHONY : AOC7.s

# target to generate assembly for a file
AOC7.cpp.s:
	$(MAKE) -f CMakeFiles/aoc7.dir/build.make CMakeFiles/aoc7.dir/AOC7.cpp.s
.PHONY : AOC7.cpp.s

AOC8.o: AOC8.cpp.o

.PHONY : AOC8.o

# target to build an object file
AOC8.cpp.o:
	$(MAKE) -f CMakeFiles/aoc8.dir/build.make CMakeFiles/aoc8.dir/AOC8.cpp.o
.PHONY : AOC8.cpp.o

AOC8.i: AOC8.cpp.i

.PHONY : AOC8.i

# target to preprocess a source file
AOC8.cpp.i:
	$(MAKE) -f CMakeFiles/aoc8.dir/build.make CMakeFiles/aoc8.dir/AOC8.cpp.i
.PHONY : AOC8.cpp.i

AOC8.s: AOC8.cpp.s

.PHONY : AOC8.s

# target to generate assembly for a file
AOC8.cpp.s:
	$(MAKE) -f CMakeFiles/aoc8.dir/build.make CMakeFiles/aoc8.dir/AOC8.cpp.s
.PHONY : AOC8.cpp.s

BinaryMatrix.o: BinaryMatrix.c.o

.PHONY : BinaryMatrix.o

# target to build an object file
BinaryMatrix.c.o:
	$(MAKE) -f CMakeFiles/binmat.dir/build.make CMakeFiles/binmat.dir/BinaryMatrix.c.o
.PHONY : BinaryMatrix.c.o

BinaryMatrix.i: BinaryMatrix.c.i

.PHONY : BinaryMatrix.i

# target to preprocess a source file
BinaryMatrix.c.i:
	$(MAKE) -f CMakeFiles/binmat.dir/build.make CMakeFiles/binmat.dir/BinaryMatrix.c.i
.PHONY : BinaryMatrix.c.i

BinaryMatrix.s: BinaryMatrix.c.s

.PHONY : BinaryMatrix.s

# target to generate assembly for a file
BinaryMatrix.c.s:
	$(MAKE) -f CMakeFiles/binmat.dir/build.make CMakeFiles/binmat.dir/BinaryMatrix.c.s
.PHONY : BinaryMatrix.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... aoc8"
	@echo "... aoc7"
	@echo "... aoc10"
	@echo "... aoc3_2"
	@echo "... aoc6"
	@echo "... aoc2"
	@echo "... rebuild_cache"
	@echo "... aoc3"
	@echo "... aoc1"
	@echo "... aoc5"
	@echo "... aoc"
	@echo "... binmat"
	@echo "... AOC.o"
	@echo "... AOC.i"
	@echo "... AOC.s"
	@echo "... AOC1.o"
	@echo "... AOC1.i"
	@echo "... AOC1.s"
	@echo "... AOC10.o"
	@echo "... AOC10.i"
	@echo "... AOC10.s"
	@echo "... AOC2.o"
	@echo "... AOC2.i"
	@echo "... AOC2.s"
	@echo "... AOC3.o"
	@echo "... AOC3.i"
	@echo "... AOC3.s"
	@echo "... AOC3_2.o"
	@echo "... AOC3_2.i"
	@echo "... AOC3_2.s"
	@echo "... AOC5.o"
	@echo "... AOC5.i"
	@echo "... AOC5.s"
	@echo "... AOC6.o"
	@echo "... AOC6.i"
	@echo "... AOC6.s"
	@echo "... AOC7.o"
	@echo "... AOC7.i"
	@echo "... AOC7.s"
	@echo "... AOC8.o"
	@echo "... AOC8.i"
	@echo "... AOC8.s"
	@echo "... BinaryMatrix.o"
	@echo "... BinaryMatrix.i"
	@echo "... BinaryMatrix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

